name: "ps-jfrog-gitbub-oidc-npm-example"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
  contents: read

jobs:
  ps-jfrog-gitbub-oidc-npm-example:
     runs-on: ubuntu-24.04
     env:
      OIDC_AUDIENCE: 'ps-jfrog-oidc'
      OIDC_PROVIDER: 'ps-jfrog-labs'
      PLATFORM_REPO: 'blr-npm-stage-virtual'
     steps:
       - name: Checkout
         uses: actions/checkout@v4
              
       - name: Setup Node npm
         uses: actions/setup-node@v4
   
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: ${{ vars.JF_URL }}
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           oidc-audience: ${{ env.OIDC_AUDIENCE }}

             #- name: Run Audit scan for the git workspace
             #run: jf audit --without-contextual-analysis --sca --secrets --sast --watches allbuilds

       - name: Set CLI Config
         run: jf npm-config --global=true --repo-resolve=$PLATFORM_REPO --repo-deploy=$PLATFORM_REPO
           
       - name: Install Dependencies
         run: jf npm install --loglevel=verbose 
       - name: pack npm
         run: jf npm pack
         
       - name: build Dockerimage 
         run: |
           pwd
           ls -la
           docker build -t 'psazuse.jfrog.io/nd-default-docker-local/cloudinary_npm:${{ github.run_number }}' .
           jf docker scan 'psazuse.jfrog.io/nd-default-docker-local/cloudinary_npm:${{ github.run_number }}' --build-name=$GITHUB_JOB --build-number=${{ github.run_number }} --vuln --fail=false --watches=notification
           jf docker push 'psazuse.jfrog.io/nd-default-docker-local/cloudinary_npm:${{ github.run_number }}' --build-name=$GITHUB_JOB --build-number=${{ github.run_number }}
           #       - name: Npm Publish
           #run: jf npm publish --build-name=$GITHUB_JOB --build-number=${{ github.run_number }}
       
       - name: Publish Build info With JFrog CLI
         run: |
          # Collect environment variables for the build
          jf rt bce $GITHUB_JOB ${{ github.run_number }}
          # Collect VCS details from git and add them to the build
          jf rt build-add-git $GITHUB_JOB ${{ github.run_number }}
          # Publish build info
          jf rt bp $GITHUB_JOB ${{ github.run_number }}

       - name: buildscan
         run: |
           sleep 30
           jf bs --vuln --fail=false $GITHUB_JOB ${{ github.run_number }}
